# Generated by Django 3.2.9 on 2021-11-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('titile', models.CharField(max_length=100)),
            ],
        ),
    ]
